version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
file_exists_behavior: OVERWRITE
BeforeInstall:
  - location: /deregister_from_elb.sh
    timeout: 300
    runas: root
AfterInstall:
  - location: /register_with_elb.sh
    timeout: 300
    runas: root
